# Pre-processed into a .js file that imports all the images
sizes:
  thumb:
    width: 400 #768
    height: 532 #1024
data:
  - name: Fruit Spread
    description: >
      Just like your favorite blueberry jam without the white sugar. It is 
      sweetened with white grape juice.
    price: 8
    photos:
      - IMG_7728.jpg
      - IMG_8734.jpg
  - name: Preserves
    description: >
      Your traditional, time-honored, yummy blueberry jam.
    price: 8
    photos:
      - IMG_7727.jpg
      - IMG_8725.jpg
  - name: Sauce
    description: >
      A bit thicker than syrup, it works great on ice-cream, cheesecake,
      and a topping for a lemon pie! No white sugar in this one.
    price: 8
    photos:
      - IMG_7729.jpg
      - IMG_8726.jpg
  - name: Pepper Jelly
    description: >
      A sweet spicey jam with a kick! Delicious with a cream cheese spread
      and crackers. Be careful, (or not) it’s addicting!
    price: 9
    photos:
      - IMG_7726.jpg
      - IMG_8727.jpg
  - name: Vinaigrette
    description: >
      great topping for salads, of course, and also as a marinade for chicken 
      or pork. Sweetened with honey for a natural goodness.
    price: 10
    photos:
      - IMG_7724.jpg
      - IMG_8728.jpg
  - name: Syrup
    description: >
      No corn syrup here, just a mouthwatering taste on those waffles and 
      pancakes.
    price: 10
    photos:
      - IMG_7725.jpg
      - IMG_8729.jpg
  - name: Scone Mix
    description: >
      Lemons and blueberries combine for the perfect Sunday morning treat of 
      a scone- one mix makes 12 scones- just add water.
    price: 10
    photos:
      - IMG_8732.jpg
      - IMG_8733.jpg
photos:
  - file: IMG_8732.jpg
    alt: Blueberry Scone Mix; Just Add Water; Made in Oregon
  - file: IMG_7727.jpg
    alt: Blueberry Preserve Jar
  - file: IMG_7729.jpg
    alt: Blueberry Sauce Jar
  - file: IMG_7726.jpg
    alt: Blueberry Pepper Jelly
  - file: IMG_7724.jpg
    alt: Blueberry Vinaigrette
  - file: IMG_7725.jpg
    alt: Blueberry Real Fruit Syrup
  - file: IMG_7728.jpg
    alt: Blueberry Fruit Spread
  - file: IMG_8733.jpg
    alt: Blueberry Scone Mix; Ingredients and Directions
  - file: IMG_8725.jpg
    alt: Blueberry Preserves ingredients
  - file: IMG_8726.jpg
    alt: Blueberry Sauce ingredients
  - file: IMG_8727.jpg
    alt: Blueberry Pepper Jelly ingredients
  - file: IMG_8728.jpg
    alt: Blueberry Vinaigrette ingredients
  - file: IMG_8729.jpg
    alt: Blueberry Syrup ingredients
  - file: IMG_8734.jpg
    alt: Blueberry Fruit Spread ingredients
